import type { Metadata } from 'next'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Theme } from '@radix-ui/themes'

import './globals.css'
import '@radix-ui/themes/styles.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <title>Kevin Shirley | Software Developer</title>
        <meta name='description' content='Experienced Software Developer specializing in front-end development within cloud environments. Pro,cient in JavaScript/TypeScriptj Node.:sj Reactj VueJsj Reduxj Firebasej and AWS.' />
      </Head>
      <body className={`${inter.className} bg-slate-900`}>
        <Theme>
          {children}
        </Theme>
      </body>
    </html>
  )
}
